export const EVENTS = {
  MODEL_CREATED: "MODEL_CREATED",
  FRIEND_REQUESTED: "FRIEND_REQUESTED",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_LOGIN_BATCH: "USER_LOGIN_BATCH",
  USER_LOGOUT_BATCH: "USER_LOGOUT_BATCH",
  FRIEND_ACCEPTED: "FRIEND_ACCEPTED",
  MESSAGE_SENT: "MESSAGE_SENT",
};
